### ISSUE TITLE
Indented bulleted lists copy across as numbered lists instead of circles

### ISSUE THREAD

**Issue by LloydBidhive** [froala/wysiwyg-editor#3539]
##### Expected behavior.
Second level indented bullet points should  be circles, not numbers.

##### Actual behavior.
Indented list copies across as numbers. 

##### Steps to reproduce the problem.
- Open the attached Word document example
- Copy the list
- Paste into our [jsFiddle](https://jsfiddle.net/xk4903gr/1/)
- Press "Keep" when the Word Paste Detected modal appears.
- Notice that the indented sub list copies across with numbers instead of the hollowed "circle" list type in the Froala toolset. 

##### Editor version.
3.0.2

##### OS.
MacOS Mojave 10.14.4 (18E226)

##### Browser.
Google Chrome Version 75.0.3770.100 (Official Build) (64-bit)

##### Attachments.
[List Items.docx](https://github.com/froala/wysiwyg-editor/files/3371244/List.Items.docx)

**Comment by casualuser** [comment]
this was fixed in 3.0.3

**Comment by LloydBidhive** [comment]
Hi @casualuser - I've just tested this again (with the originally attached docx file) and it doesn't appear fixed. 

The second level hollow bullet points are still copying across as a numbered list.

We updated to 3.0.3 within the last week. Issue [3546](https://github.com/froala/wysiwyg-editor/issues/3546) you just closed with 3.0.3 works, however this one still does not. 

See below gif between Word and our [jsFiddle](https://jsfiddle.net/xk4903gr/1/)


![bullet lists](https://user-images.githubusercontent.com/41405678/61423118-ede28000-a951-11e9-8362-b359af6b17ab.gif)
