### ISSUE TITLE
Applying formatting to a selection is working in an unexpected way in Firefox

### ISSUE THREAD

**Issue by chrisdeeming** [froala/wysiwyg-editor#3559]
##### Expected behavior.
Only the highlighted selection should be formatted.

##### Actual behavior.
Multiple areas receive the formatting.

##### Steps to reproduce the problem.
https://jsfiddle.net/70rfjnux/1/

1. Highlight "Line 1"
2. Click B to bold
3. Observe that both **Line 1** and **Line 3** receive the formatting.

##### Editor version.
2.9.6

##### OS.
Any

##### Browser.
Firefox

##### Recording.
https://i.imgur.com/ntnRPEM.mp4

**Comment by casualuser** [comment]
Hello,
This is known issue and it is already fixed in code represented in `v2` branch of this repo.
It will be released in 2.9.7 version which planned to Sept. 
At the moment you can pick up files directly from repo or look at our v3

**Comment by chrisdeeming** [comment]
September... It’s currently July. The current release cycles are far too slow.

**Comment by GH-Rake** [comment]
Looking forward to this fix, somewhat desperately ... :)

**Comment by chrisdeeming** [comment]
@stefanneculai @casualuser I appreciate that you are hard at work on v3 but you have to appreciate that you will still have customers who are still using v2.

2.9.7 was planned for September. You missed that date.

When in October is the 2.9.7 release planned for, or is it delayed to November? Why is it the case that the speed of releases (pre-dating even before v3) has slowed down significantly?
