### ISSUE TITLE
Froala thinks the user is editing a bullet list when the editor itself is in a bullet list

### ISSUE THREAD

**Issue by chrisdavies** [froala/wysiwyg-editor#853]
I have a scenario that is like this:

```html
<ul>
  <li>
    <textbox class="froala-editable">
    </textbox>
  </li>
</ul>
```

When I turn the `textbox` element into a Froala editor, the toolbar shows that the user is editing a bullet list. It's probably doing a `.closest("ul")` or something, and not determining if the UL it finds is actually within the editor.

**Comment by chrisdavies** [comment]
Here's a screenshot:

<img width="627" alt="screen shot 2015-10-12 at 4 52 00 pm" src="https://cloud.githubusercontent.com/assets/833377/10438450/9a1668ec-7101-11e5-9742-08dab8efcec1.png">

**Comment by stefanneculai** [comment]
It has been fixed some time ago: https://github.com/froala/wysiwyg-editor/issues/772. Are you using the master version?

**Comment by chrisdavies** [comment]
Evidently not! Where do I get the master version?

**Comment by stefanneculai** [comment]
https://github.com/froala/wysiwyg-editor

**Comment by chrisdavies** [comment]
Ah. Ha ha. You mean literally, the git master version. Thanks!

**Comment by chrisdavies** [comment]
Hm. I pulled master, dropped it in, and am still seeing that behavior.

I'm using the latest version of Chrome.

**Comment by stefanneculai** [comment]
Could you please make a jsFiddle for it? Also, could you make sure that you have updated the lists plugin as well?

**Comment by chrisdavies** [comment]
Do you have a CDN I can use to include the Froala files?

**Comment by stefanneculai** [comment]
Sure. https://cdnjs.com/libraries/froala-editor

**Comment by chrisdavies** [comment]
http://jsbin.com/ralulo/edit?html,js,output

**Comment by chrisdavies** [comment]
That shows the repro.

**Comment by chrisdavies** [comment]
I have access to your source code, but I forget how to get to it. (We are on the OEM plan.) But in the minified list plugin, here is how to fix the bug:

```javascript
function j(c, d) {
            var e = a(b.selection.element());
            if (e.get(0) != b.$el.get(0)) {
                var f = e.get(0);
                "LI" != f.tagName && (f = e.parents("li").get(0)), f && f.parentNode.tagName == d && b.$el.get(0).contains(f.parentNode) && c.addClass("fr-active")
            }
        }
```

This bit here: `b.$el.get(0).contains(f.parentNode)` is the key. It is a check that the editor's element actually contains the list.

**Comment by chrisdavies** [comment]
Dunno if this is against the rules, but here is the unminified patch (a modification of line 196 in lists.js):

```javascript
if (li && li.parentNode.tagName == tag_name && editor.$el.get(0).contains(li.parentNode)) {
    $btn.addClass('fr-active');
}
```

**Comment by stefanneculai** [comment]
It looks the other fix was only for ENTER_BR mode. Last commit fixes it. Thanks for digging. :+1:

**Comment by chrisdavies** [comment]
Thanks for the fast response!
