### ISSUE TITLE
imageUploadToS3 not working anymore after upgrading to v2.0.1

### ISSUE THREAD

**Issue by lou** [froala/wysiwyg-editor#939]
I have just updated Froala from version 1.2.8 to 2.0.1 and the imageUploadToS3 does not work anymore.
I didn't find anything in the "upgrade from v1 documentation" (https://www.froala.com/wysiwyg-editor/docs/migrate-from-v1) that could help me.

I'm not sur if it could help but here the screenshots of my Firefox console.
![screen shot 2015-11-24 at 4 19 25 pm](https://cloud.githubusercontent.com/assets/27757/11371198/9f39e7d0-92c7-11e5-8e82-fe3c87f58f30.png)
![screen shot 2015-11-24 at 4 19 48 pm](https://cloud.githubusercontent.com/assets/27757/11371206/a5bf93b6-92c7-11e5-86d2-a9f1ca90bea1.png)

**Comment by stefanneculai** [comment]
It's a common problem we see since the new version. Specifying the region should fix the problem for you.

**Comment by lou** [comment]
Thanks for the quick answer @stefanneculai.
I have actually no more CORS error in my console after specifying the region.
But this is not working I have the message `Something went wrong. Please try again.`
And the OPTIONS call to S3 does not return anything (status code or header).

**Comment by stefanneculai** [comment]
I am closing this because it's not an editor issue but a configuration problem. If you have a license that includes support please contact us via our website.

**Comment by lou** [comment]
Ok I finally found the answer.
The documentation (https://www.froala.com/wysiwyg-editor/docs/options#imageUploadToS3) says that you have to pass a `region` option, which is confusing because indeed you need to pass for example `s3-us-east-1` but what AWS calls a region is only `us-east-1` (http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region).
Therefore the documentation should be updated to specify `s3-region`.

I ask for support and they told me I have to pay for the support license.
I think this is a basic configuration which is not well documented and I already have a license for 99$ so it would have been nice to just take 2 minutes to check on my configuration.

Anyway the library is totally worth 99$, thanks for the great work.

**Comment by raistlinthewiz** [comment]
@lou, what's the answer?

I'm also on us standart and tried 's3' as the region name but still no luck.

Can you please clarify your answer?
